import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'ko' | 'en';

const STORAGE_KEY = 'app_language';
const DEFAULT_LANGUAGE: Language = 'ko';

// 지금은 설정 화면 전체 + 오늘 탭 일부(주요 버튼/안내 문구)만 번역돼 있음 — 전체 화면 적용은
// 필요할 때 이 사전에 키를 계속 추가해나가는 방식으로 확장한다
const TRANSLATIONS = {
  ko: {
    'settings.timeSettings': '시간대 설정',
    'settings.basicSettings': '기본 설정',
    'settings.themeColor': '테마 색',
    'settings.themeColorDesc': '테마색을 변경할 수 있어요',
    'settings.font': '폰트',
    'settings.fontDesc': '루틴 제목 등에 쓰이는 폰트를 바꿀 수 있어요',
    'settings.language': '언어',
    'settings.languageDesc': '앱에서 사용할 언어를 선택할 수 있어요',
    'settings.languageKorean': '한국어',
    'settings.languageEnglish': 'English',
    'settings.signOut': '로그아웃',
    'settings.signOutConfirmTitle': '로그아웃 하시겠어요?',
    'settings.signOutConfirmDesc': '다시 로그인해서 계속 사용할 수 있어요',
    'settings.cancel': '취소',
    'settings.privacyPolicy': '개인정보처리방침',
    'settings.notifications': '알림',
    'settings.notificationsDesc': '알림 소리·진동을 켜고 끌 수 있어요',
    'settings.notifSound': '알림 소리',
    'settings.notifVibration': '진동',
    'settings.exactAlarmPermission': '정확한 시간에 알림 받기',
    'settings.notifTroubleshoot': '알림이 안 온다면',
    'settings.contact': '문의하기',
    'settings.version': '버전',
    'settings.deleteAccount': '회원탈퇴',
    'settings.deleteAccountConfirmTitle': '정말 탈퇴하시겠어요?',
    'settings.deleteAccountConfirmDesc': '모든 루틴, 기록, 일기, 사진 등 데이터가 영구적으로 삭제되며 복구할 수 없습니다.',
    'settings.deleteAccountError': '회원탈퇴 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
    'settings.deleteAccountHint': '꾸욱 눌러야 활성화(3초 안에 클릭)',
    'photoDiary.createButton': '사진일기 만들기',
    'photoDiary.viewButton': '사진일기 보기/수정',
    'photoDiary.chooseSourceTitle': '사진 추가',
    'photoDiary.takePhoto': '사진 찍기',
    'photoDiary.pickFromLibrary': '사진 불러오기',
    'photoDiary.changePhoto': '사진 바꾸기',
    'photoDiary.chooseModeTitle': '무엇을 적을까요?',
    'photoDiary.modeText': '일기 적기',
    'photoDiary.modeRoutines': '오늘 루틴 고르기',
    'photoDiary.textPlaceholder': '오늘 하루를 적어보세요',
    'photoDiary.notePlaceholder': '자유롭게 적어보세요',
    'photoDiary.addNote': '메모 추가',
    'photoDiary.routineColorToggle': '루틴 색 강조',
    'photoDiary.emptyRoutines': '그날 예정된 루틴이 없어요',
    'photoDiary.hiddenSectionTitle': '숨긴 항목',
    'photoDiary.addBack': '다시 추가',
    'photoDiary.saveImage': '이미지로 저장',
    'photoDiary.share': '공유하기',
    'photoDiary.savedToGalleryTitle': '사진 보관함에 저장했어요',
    'photoDiary.deleteButton': '사진일기 삭제',
    'photoDiary.deleteConfirmTitle': '사진일기를 삭제하시겠어요?',
    'photoDiary.deleteConfirmDesc': '삭제하면 되돌릴 수 없어요.',
    'photoDiary.permissionTitle': '권한이 필요해요',
    'photoDiary.cameraPermissionDesc': '사진일기 사진을 촬영하려면 카메라 접근을 허용해주세요.',
    'photoDiary.libraryPermissionDesc': '사진일기에 넣을 사진을 고르려면 사진 보관함 접근을 허용해주세요.',
    'photoDiary.mediaLibraryPermissionDesc': '사진일기를 사진 보관함에 저장하려면 접근을 허용해주세요.',
    'photoDiary.errorLoad': '사진일기를 불러오지 못했어요.',
    'photoDiary.errorSave': '사진일기 저장에 실패했어요.',
    'photoDiary.errorDelete': '사진일기 삭제에 실패했어요.',
    'photoDiary.errorSaveImage': '이미지 저장/공유에 실패했어요.',
    'today.video': '영상',
    'today.diary': '일기',
    'today.presets': '모음집',
    'today.myRoutines': '내 루틴',
    'today.list': '리스트',
    'today.timeline': '타임라인',
    'today.llmBanner': '말로 루틴 추가하기',
    'today.empty': '오늘 할 루틴이 없어요',
    'today.edit': '수정',
    'today.cancelRecord': '기록삭제',
    'today.skipToday': '오늘 삭제',
    'today.close': '닫기',
    'today.save': '저장',
    'today.timelineEmpty': '시간 정보가 있는 루틴이 없어요',
    'today.dontShowAgain': '다시 안 보기',
    'today.errorLoad': '루틴을 불러오지 못했어요. 다시 시도해주세요.',
    'today.errorCheck': '체크 처리에 실패했어요.',
    'today.errorDelete': '삭제에 실패했어요.',
    'today.errorSaveRecord': '기록 저장에 실패했어요.',
    'today.holidayPrefix': '오늘은',
    'today.daySuffix': '일',
    'today.completedLabel': '오늘 완료',
    'today.bestStreakLabel': '최고 기록',
    'calendar.week': '주',
    'calendar.month': '월',
    'calendar.streakUnit': '일 연속 · 역대 최고',
    'calendar.noStreakYet': '아직 최고 기록이 없어요',
    'calendar.legendDone': '다 완료',
    'calendar.legendPartial': '일부 완료',
    'calendar.legendMissed': '필수 놓침',
    'calendar.viewDiary': '일기 보기',
    'calendar.memoSection': '메모',
    'calendar.noMemo': '메모 없음',
    'calendar.memoEdit': '수정',
    'calendar.memoDelete': '삭제',
    'calendar.memoEditComplete': '수정완료',
    'calendar.memoAdd': '추가',
    'calendar.memoCancelEdit': '수정 취소',
    'calendar.memoPlaceholder': '메모 입력 (예: 내일 시험치기)',
    'calendar.todayRoutines': '오늘의 루틴',
    'calendar.noRoutinesThisDay': '이 날은 예정된 루틴이 없어요',
    'calendar.errorCheck': '체크 처리에 실패했어요.',
    'calendar.errorSaveMemo': '메모 저장에 실패했어요.',
    'calendar.errorDeleteMemo': '메모 삭제에 실패했어요.',
    'calendar.weekdaySun': '일',
    'calendar.weekdayMon': '월',
    'calendar.weekdayTue': '화',
    'calendar.weekdayWed': '수',
    'calendar.weekdayThu': '목',
    'calendar.weekdayFri': '금',
    'calendar.weekdaySat': '토',
    'stats.errorLoad': '통계를 불러오지 못했어요.',
    'stats.retry': '다시 시도',
    'stats.emptyNoRecords': '아직 기록이 없어요, 루틴을 먼저 체크해보세요',
    'stats.hide': '숨기기',
    'stats.currentStreak': '현재 스트릭',
    'stats.bestStreak': '최고 스트릭',
    'stats.allTimeRate': '전체 기간 수행률',
    'stats.weekly': '주간',
    'stats.monthly': '월별',
    'stats.last7DaysRate': '최근 7일 수행률',
    'stats.last30DaysRate': '최근 30일 수행률',
    'stats.completedSuffix': '완료',
    'stats.categoryAll': '전체',
    'stats.categoryWeekday': '평일',
    'stats.categoryWeekend': '주말',
    'stats.summaryNote': '삭제된 루틴의 기록도 삭제 전 날짜까지는 위 수행률에 포함돼 있어요',
    'stats.emptyCategoryNoRoutines': '이 카테고리에 해당하는 루틴이 없어요',
    'stats.emptyAllHidden': '표시할 통계가 없어요 (전부 숨김 상태)',
    'stats.emptyNoActiveRoutines': '진행 중인 루틴이 없어요',
    'stats.hiddenCollapse': '숨긴 항목 접기 ▲',
    'stats.hiddenExpandPrefix': '숨긴 항목 ',
    'stats.hiddenExpandSuffix': '개 보기 ▼',
    'stats.unhide': '다시 보이기',
    'myRoutines.filterAll': '전체',
    'myRoutines.filterDaily': '매일',
    'myRoutines.filterWeekday': '평일',
    'myRoutines.filterWeekend': '주말',
    'myRoutines.filterCustom': '특정 요일',
    'myRoutines.filterOnce': '1회성',
    'myRoutines.onceActive': '1회성',
    'myRoutines.oncePast': '지난 1회성',
    'myRoutines.repeatDaily': '매일',
    'myRoutines.repeatWeekday': '평일',
    'myRoutines.repeatWeekend': '주말',
    'myRoutines.repeatCustom': '특정 요일',
    'myRoutines.repeatOnce': '1회성',
    'myRoutines.noScheduledTime': '시간 미지정',
    'myRoutines.paused': '일시정지',
    'myRoutines.requiredSuffix': ' · 필수',
    'myRoutines.skippedTodaySuffix': ' · 오늘 제외됨',
    'myRoutines.addToToday': '오늘 목록에 추가',
    'myRoutines.delete': '삭제',
    'myRoutines.errorUnskip': '되돌리기에 실패했어요.',
    'myRoutines.errorLoad': '루틴을 불러오지 못했어요.',
    'myRoutines.errorDelete': '삭제에 실패했어요.',
    'myRoutines.subtitle': '전체 루틴을 보고 수정할 수 있어요',
    'myRoutines.routineTrash': '루틴 복구',
    'myRoutines.groupRepeat': '반복 주기',
    'myRoutines.groupPreset': '모음집',
    'myRoutines.noPresets': '아직 만든 모음집이 없어요.',
    'myRoutines.selectedCountSuffix': '개 선택됨',
    'myRoutines.selectAll': '전체 선택',
    'myRoutines.deselectAll': '전체 해제',
    'myRoutines.bulkDelete': '선택 삭제',
    'myRoutines.dragHint': '≡ 를 길게 눌러 드래그하면 순서를 바꿀 수 있어요',
    'myRoutines.emptyChoosePreset': '위에서 모음집을 골라주세요',
    'myRoutines.emptyNoMatch': '해당하는 루틴이 없어요',
    'myRoutines.deleteRoutineTitle': '루틴을 삭제할까요?',
    'myRoutines.deleteRoutineOnly': '루틴만 삭제',
    'myRoutines.deletePresetToo': '모음집도 삭제',
    'myRoutines.deleteSelectedTitle': '선택한 루틴을 삭제할까요?',
    'presets.errorLoad': '모음집을 불러오지 못했어요.',
    'presets.applyError': '적용에 실패했어요. 다시 시도해주세요.',
    'presets.deleteError': '삭제에 실패했어요. 다시 시도해주세요.',
    'presets.pauseError': '처리에 실패했어요. 다시 시도해주세요.',
    'presets.deleteTitle': '모음집을 삭제할까요?',
    'presets.newPreset': '+ 새 모음집 만들기',
    'presets.empty': '아직 만든 모음집이 없어요. 평일 일정, 주말, 학원처럼 자주 쓰는 루틴 묶음을 만들어보세요.',
    'presets.skipHolidaysSuffix': ' · 공휴일 제외',
    'presets.applyToToday': '오늘 목록에 적용',
    'presets.edit': '수정',
    'presets.bulkManageLabel': '이 모음집으로 만든 루틴 일괄 관리',
    'presets.pauseAll': '전체 비활성화',
    'presets.activateAll': '전체 활성화',
    'common.check': '체크',
    'common.tracking': '트래킹(숫자)',
    'common.exactTime': '정확한 시간',
    'common.instantTime': '시간 체크',
    'common.slot': '슬롯',
    'common.required': '필수',
    'common.done': '완료',
    'common.add': '추가',
    'common.confirm': '확인',
    'presetForm.errorLoadSlots': '슬롯 정보를 불러오지 못했어요.',
    'presetForm.errorLoadFavorites': '즐겨찾기를 불러오지 못했어요.',
    'presetForm.errorLoadPreset': '모음집 정보를 불러오지 못했어요.',
    'presetForm.errorNameRequired': '모음집 이름을 입력해주세요.',
    'presetForm.errorDaysRequired': '반복할 요일을 하나 이상 선택해주세요.',
    'presetForm.errorItemsRequired': '항목을 하나 이상 추가해주세요.',
    'presetForm.errorItemTitleRequired': '모든 항목의 제목을 입력해주세요.',
    'presetForm.errorTrackingUnitRequired': '트래킹 항목은 단위를 입력해주세요.',
    'presetForm.errorSave': '저장에 실패했어요. 다시 시도해주세요.',
    'presetForm.errorDelete': '삭제에 실패했어요.',
    'presetForm.nameLabel': '모음집 이름',
    'presetForm.namePlaceholder': '예: 평일 일정',
    'presetForm.repeatLabel': '반복',
    'presetForm.skipHolidays': '공휴일 제외',
    'presetForm.itemsSection': '항목',
    'presetForm.itemTitlePlaceholder': '루틴 제목',
    'presetForm.trackingUnitPlaceholder': '직접 입력 (예: 회)',
    'presetForm.addItem': '+ 항목 추가',
    'presetForm.addFromFavorite': '즐겨찾기에서 추가',
    'presetForm.saveEdit': '수정 완료',
    'presetForm.create': '만들기',
    'presetForm.deletePreset': '모음집 삭제',
    'presetForm.createdTitle': '모음집을 만들었어요',
    'presetForm.updatedTitle': '오늘 목록에 반영했어요',
    'presetForm.addedSuffix': '추가',
    'presetForm.removedSuffix': '삭제',
    'favorites.errorDelete': '삭제에 실패했어요.',
    'favorites.addFavorite': '+ 즐겨찾기 추가',
    'favorites.empty': '자주 쓰는 루틴을 즐겨찾기로 저장해두면, 루틴 추가나 모음집 만들 때 바로 불러올 수 있어요.',
    'favorites.sectionCheck': '체크형',
    'favorites.sectionTracking': '트래킹형',
    'favoriteForm.errorLoadSlots': '슬롯 정보를 불러오지 못했어요.',
    'favoriteForm.errorLoadFavorite': '즐겨찾기 정보를 불러오지 못했어요.',
    'favoriteForm.errorTitleRequired': '제목을 입력해주세요.',
    'favoriteForm.errorTrackingUnitRequired': '트래킹 단위를 입력해주세요.',
    'favoriteForm.errorSlotRequired': '슬롯을 선택해주세요.',
    'favoriteForm.errorSave': '저장에 실패했어요.',
    'favoriteForm.errorDelete': '삭제에 실패했어요.',
    'favoriteForm.titleLabel': '제목',
    'favoriteForm.titlePlaceholder': '예: 스트레칭',
    'favoriteForm.typeLabel': '타입',
    'favoriteForm.unitLabel': '단위',
    'favoriteForm.timeLabel': '시간',
    'favoriteForm.saveEdit': '수정 완료',
    'favoriteForm.addToFavorites': '즐겨찾기에 추가',
    'videos.myVideos': '내 영상',
    'videos.recommended': '추천 영상',
    'categoryVideoGrid.addCategory': '+ 카테고리',
    'categoryVideoGrid.addMyVideo': '+ 내 영상 추가',
    'categoryVideoGrid.renameCategory': '이름 수정',
    'categoryVideoGrid.deletedCategoriesLink': '삭제된 카테고리',
    'categoryVideoGrid.emptyVideosLine1': '아직 추가한 영상이 없어요',
    'categoryVideoGrid.emptyVideosLine2': '추천 영상에서 가져오거나 직접 추가해보세요',
    'categoryVideoGrid.addVideoModalTitle': '내 영상 추가',
    'categoryVideoGrid.addVideoModalDesc': '유튜브 링크를 붙여넣으면 제목/채널 정보를 자동으로 가져와요. 나에게만 보여요.',
    'categoryVideoGrid.categoryModalTitleCreate': '카테고리 추가',
    'categoryVideoGrid.categoryModalTitleRename': '카테고리 이름 수정',
    'categoryVideoGrid.categoryNamePlaceholder': '카테고리 이름',
    'categoryVideoGrid.trashModalDesc': '내가 만든 카테고리는 삭제 후 3일 안에 여기서 복구할 수 있어요. 3일이 지나면 안의 영상까지 완전히 삭제돼요.',
    'categoryVideoGrid.emptyDeletedCategories': '삭제된 카테고리가 없어요.',
    'categoryVideoGrid.restore': '복구',
    'categoryVideoGrid.hardDelete': '완전삭제',
    'categoryVideoGrid.hiddenDefaultsSectionTitle': '삭제한 기본 카테고리',
    'categoryVideoGrid.hiddenDefaultsDesc': '기본 카테고리는 3일 제한 없이 언제든 다시 만들 수 있어요. 저희가 기본 제공하는 영상은 자동으로 다시 채워지지만, 내가 직접 추가했던 영상은 이미 지워진 상태라 돌아오지 않아요.',
    'categoryVideoGrid.emptyHiddenDefaults': '삭제한 기본 카테고리가 없어요.',
    'categoryVideoGrid.recreateDefaults': '기본 카테고리 생성',
    'categoryVideoGrid.confirmDeleteVideoTitleLinked': '연결된 루틴이 있어요',
    'categoryVideoGrid.confirmDeleteVideoTitleSimple': '이 영상을 삭제할까요?',
    'categoryVideoGrid.deleteFailedTitle': '삭제 실패',
    'categoryVideoGrid.deleteVideoFailedDefault': '영상을 삭제하지 못했어요.',
    'categoryVideoGrid.alreadyAddedError': '이미 이 카테고리에 추가된 영상이에요.',
    'categoryVideoGrid.addVideoFailedDefault': '영상을 추가하지 못했어요.',
    'categoryVideoGrid.saveCategoryFailedDefault': '저장하지 못했어요.',
    'categoryVideoGrid.deleteCategoryConfirmTitle': '이 카테고리를 삭제할까요?',
    'categoryVideoGrid.deleteDefaultCategoryWarningTitle': '추가한 영상은 복구되지 않아요',
    'categoryVideoGrid.deleteCategoryFailed': '카테고리를 삭제하지 못했어요.',
    'categoryVideoGrid.recreateFailedTitle': '실패',
    'categoryVideoGrid.recreateFailedDesc': '기본 카테고리를 다시 만들지 못했어요.',
    'categoryVideoGrid.restoreFailedTitle': '복구 실패',
    'categoryVideoGrid.restoreFailedDesc': '복구하지 못했어요.',
    'categoryVideoGrid.hardDeleteConfirmTitle': '완전히 삭제할까요?',
    'categoryVideoGrid.hardDeleteConfirmDesc': '3일을 기다리지 않고 지금 바로 완전히 삭제돼요. 되돌릴 수 없어요.',
    'categoryVideoGrid.hardDeleteFailedDesc': '삭제하지 못했어요.',
    'recommendedVideoGrid.notReady': '준비 중입니다',
    'recommendedVideoGrid.addToMyGrid': '+ 내 그리드에 추가',
    'recommendedVideoGrid.pickCategoryTitle': '어느 카테고리에 추가할까요?',
    'recommendedVideoGrid.pickCategoryEmpty': '"내 영상" 탭에서 카테고리를 먼저 만들어주세요.',
    'recommendedVideoGrid.addFailedTitle': '추가 실패',
    'recommendedVideoGrid.addFailedDefault': '영상을 추가하지 못했어요.',
    'videoPlayer.loadFailed': '영상을 불러올 수 없어요',
    'videoPlayer.visitChannel': '채널 방문 ›',
    'common.minuteShort': '분',
    'common.hourShort': '시간',
    'routineForm.errorLoadRoutine': '루틴 정보를 불러오지 못했어요.',
    'routineForm.errorFavoriteApply': '즐겨찾기 추가에 실패했어요.',
    'routineForm.photoUploadFailedTitle': '저장은 됐어요',
    'routineForm.photoUploadFailedDesc': '다만 사진 업로드는 실패했어요. 나중에 다시 첨부해주세요.',
    'routineForm.photoPermissionTitle': '사진 접근 권한이 꺼져있어요',
    'routineForm.photoPermissionDesc': '기기 설정에서 사진 접근 권한을 허용해주세요.',
    'routineForm.loadFromFavorite': '즐겨찾기에서 불러오기',
    'routineForm.favoriteHintLoad': '저장해둔 루틴 템플릿을 불러와서 바로 추가하거나, 수정해서 추가할 수 있어요.',
    'routineForm.titlePlaceholder': '예: 아침 물 마시기',
    'routineForm.instantHint': '"8시 기상"처럼 시간을 차지하지 않고 그 시간에 체크만 해요.',
    'routineForm.minus30': '-30분',
    'routineForm.plus30': '+30분',
    'routineForm.plus1h': '+1시간',
    'routineForm.plus2h': '+2시간',
    'routineForm.reset': '초기화',
    'routineForm.videoConnectLabel': '영상 연결',
    'routineForm.selectVideo': '영상 선택하기',
    'routineForm.memoLabel': '메모',
    'routineForm.memoPlaceholder': '이 루틴에 대해 간단히 적어두세요 (선택)',
    'routineForm.photoLabel': '사진',
    'routineForm.photoAttached': '사진 1장 첨부됨',
    'routineForm.addPhoto': '사진 추가하기',
    'routineForm.addToFavoritesLabel': '즐겨찾기에 추가',
    'routineForm.addToFavoritesHint': '켜두면 이 내용을 템플릿으로 저장해서 다음에 또 빠르게 추가할 수 있어요.',
    'routineForm.deleteRoutineButton': '루틴삭제',
    'routineForm.applyNow': '바로 추가',
    'routineForm.applyToFormEdit': '수정해서 추가',
    'slotSettings.errorLoad': '슬롯 정보를 불러오지 못했어요.',
    'slotSettings.errorSave': '저장에 실패했어요.',
    'slotSettings.notifyPermissionTitle': '알림 권한이 꺼져있어요',
    'slotSettings.notifyPermissionDesc': '기기 설정에서 알림 권한을 허용해주세요.',
    'slotSettings.noticeDesc': '슬롯 알림을 켜면 그 시간대 시작 시각에 매일 알림이 와요. "자기전" 슬롯 알림을 켜두면, 그 시각까지 필수 루틴을 다 못했을 때만 리마인더 알림도 같이 와요. "메모 알림"은 아침 루틴 알림과 별개로 켜고 끌 수 있고, 둘 다 켜져 있는 날은 아침 시각에 알림 하나로 합쳐서 와요.',
    'slotSettings.noticeNote': 'ⓘ 아침·메모 알림은 앱을 열 때마다 다음 발송 시각을 다시 계산해요. 며칠 연속 앱을 안 열면 그 사이엔 안 올 수 있으니, 알림이 안 온다면 앱을 한 번 열어주세요.',
    'slotSettings.modeCheck': '체크형',
    'slotSettings.modeExact': '정확한 시간',
    'slotSettings.hintInstant': '정확히 이 시각에 체크해요 (예: 아침 7시)',
    'slotSettings.hintExact': '이 시간대 전체를 슬롯으로 써요 (예: 아침 7시~8시)',
    'slotSettings.memoNotifyLabel': '메모 알림',
    'slotSettings.memoNotifyHint': '이 시간에, 아침 루틴 알림과 별개로 켜고 꺼요.',
    'routineTrash.errorRestore': '복구에 실패했어요.',
    'routineTrash.errorCleanup': '정리에 실패했어요.',
    'routineTrash.cleanup': '정리',
    'routineTrash.selectCleanup': '선택 정리',
    'routineTrash.descLine1': '삭제된 루틴은 여기서 언제든 복구할 수 있어요. 완료 기록도 계속 안전하게 보관되니 걱정 마세요.',
    'routineTrash.descLine2': '모음집(루틴 묶음)은 2주 안에 복구하지 않으면 자동으로 삭제돼요. 2주를 기다리지 않고 바로 삭제하고 싶다면 "선택 정리"를 눌러주세요(연결된 루틴은 지워지지 않아요).',
    'routineTrash.empty': '삭제된 항목이 없어요.',
    'routineTrash.restorePreset': '모음집 복구',
    'routineTrash.cleanupConfirmTitle': '정리할까요?',
    'routineTrash.cleanupConfirmDo': '정리하기',
    'llmInput.quotaTitle': '무료 AI 배치 횟수를 모두 사용했어요',
    'llmInput.quotaBody': '요금제는 곧 출시돼요, 조금만 기다려주세요! "매일 아침 7시" 처럼 간단한 문장은 AI 없이도 계속 무료로 쓸 수 있어요.',
    'llmInput.tryPlainAgain': '간단한 문장으로 다시 써보기',
    'llmInput.addManually': '직접 추가하기',
    'llmInput.remainingQuotaPrefix': '남은 AI 배치 ',
    'llmInput.remainingQuotaSuffix': '회',
    'llmInput.placeholder': '예: 매일 아침 7시에 물 8잔 마시기',
    'llmInput.hint': '이런 걸 넣으면 더 정확해요 — 언제(매일·평일·월수금) · 몇 시(아침 7시) · 꼭 할 것(꼭·반드시) · 횟수(물 8잔·30분). 문장이 복잡하면 아래 "AI로 정확하게 분석" 버튼을 눌러보세요.',
    'llmInput.errorBody': '지금은 AI 배치가 잠시 쉬고 있어요. 복구까지 시간이 걸릴 수 있으니, 지금은 직접 추가하는 걸 추천해요.',
    'llmInput.retry': '다시 시도',
    'llmInput.analyzing': '분석 중...',
    'llmInput.previewButton': '미리보기 만들기',
    'llmInput.aiAnalyzing': 'AI가 분석 중...',
    'llmInput.aiAnalyzeButton': 'AI로 정확하게 분석',
    'diary.errorLoad': '일기를 불러오지 못했어요.',
    'diary.errorSave': '저장에 실패했어요. 다시 시도해주세요.',
    'diary.errorDelete': '삭제에 실패했어요.',
    'diary.deleteConfirmTitle': '일기를 삭제할까요?',
    'diary.deleteConfirmDesc': '삭제하면 되돌릴 수 없어요.',
    'diary.placeholder': '오늘 하루 어땠나요?',
    'diary.deleteButton': '일기 삭제',
    'diary.titleSuffix': '일기',
    'login.subtitle': '말하듯 적으면 루틴이 짜여요',
    'login.google': '구글로 시작하기',
    'login.kakao': '카카오로 시작하기',
    'onboarding.headlineLine1': '나만의 느낌으로',
    'onboarding.headlineLine2': '시작해볼까요?',
    'onboarding.subhead': '주색·폰트·언어는 설정에서 언제든 다시 바꿀 수 있어요',
    'onboarding.themeColor': '테마 색',
    'onboarding.font': '폰트',
    'onboarding.language': '언어',
    'onboarding.start': '시작하기',
    'nav.preset': '모음집',
    'nav.favorites': '즐겨찾기',
    'nav.videoPlayer': '영상 재생',
    'nav.tabToday': '오늘',
    'nav.tabCalendar': '캘린더',
    'nav.tabStats': '통계',
    'favoritePicker.title': '즐겨찾기',
    'favoritePicker.empty': '저장된 즐겨찾기가 없어요. 아래 "즐겨찾기 관리"에서 만들어보세요.',
    'favoritePicker.manage': '즐겨찾기 관리',
    'videoPicker.title': '영상 연결',
    'slot.morning': '아침',
    'slot.lunch': '점심',
    'slot.evening': '저녁',
    'slot.beforeSleep': '자기전',
    'trackingUnit.cup': '잔',
    'trackingUnit.count': '개',
    'trackingUnit.minute': '분',
    'trackingUnit.page': '페이지',
    'trackingUnit.km': 'km',
    'videoCategory.exercise': '운동',
    'videoCategory.beauty': '뷰티',
    'videoCategory.reading': '독서',
    'videoCategory.morningRoutine': '모닝루틴',
    'videoCategory.mindfulness': '마인드풀니스',
    'videoCategory.study': '공부/자기계발',
    'accentColor.cloud': '구름색',
    'accentColor.black': '검정',
    'accentColor.yellow': '노랑',
    'accentColor.sage': '그린',
    'accentColor.rose': '로즈',
    'today.addRoutine': '+ 루틴 추가',
    'font.default': '기본 폰트',
    'font.rounded': '동글 폰트',
  },
  en: {
    'settings.timeSettings': 'Time Settings',
    'settings.basicSettings': 'Basic Settings',
    'settings.themeColor': 'Theme Color',
    'settings.themeColorDesc': 'You can change the theme color here.',
    'settings.font': 'Font',
    'settings.fontDesc': 'You can change the font used for routine titles and more.',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose the language the app is displayed in.',
    'settings.languageKorean': 'Korean',
    'settings.languageEnglish': 'English',
    'settings.signOut': 'Sign Out',
    'settings.signOutConfirmTitle': 'Are you sure you want to sign out?',
    'settings.signOutConfirmDesc': 'You can sign back in anytime to keep using the app.',
    'settings.cancel': 'Cancel',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Turn notification sound and vibration on or off.',
    'settings.notifSound': 'Sound',
    'settings.notifVibration': 'Vibration',
    'settings.exactAlarmPermission': 'Get notifications at the exact time',
    'settings.notifTroubleshoot': "Not getting notifications?",
    'settings.contact': 'Contact us',
    'settings.version': 'Version',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountConfirmTitle': 'Are you sure you want to delete your account?',
    'settings.deleteAccountConfirmDesc': 'All routines, records, diary entries, photos, and other data will be permanently deleted and cannot be recovered.',
    'settings.deleteAccountError': 'Something went wrong while deleting your account. Please try again shortly.',
    'settings.deleteAccountHint': 'Hold to activate (tap within 3s)',
    'photoDiary.createButton': 'Create photo diary',
    'photoDiary.viewButton': 'View/edit photo diary',
    'photoDiary.chooseSourceTitle': 'Add a photo',
    'photoDiary.takePhoto': 'Take a photo',
    'photoDiary.pickFromLibrary': 'Choose from library',
    'photoDiary.changePhoto': 'Change photo',
    'photoDiary.chooseModeTitle': 'What would you like to write?',
    'photoDiary.modeText': 'Write freely',
    'photoDiary.modeRoutines': "Pick today's routines",
    'photoDiary.textPlaceholder': 'Write about your day',
    'photoDiary.notePlaceholder': 'Write freely here',
    'photoDiary.addNote': 'Add note',
    'photoDiary.routineColorToggle': 'Color routines',
    'photoDiary.emptyRoutines': 'No routines were scheduled that day',
    'photoDiary.hiddenSectionTitle': 'Hidden items',
    'photoDiary.addBack': 'Add back',
    'photoDiary.saveImage': 'Save as image',
    'photoDiary.share': 'Share',
    'photoDiary.savedToGalleryTitle': 'Saved to your photo library',
    'photoDiary.deleteButton': 'Delete photo diary',
    'photoDiary.deleteConfirmTitle': 'Delete this photo diary?',
    'photoDiary.deleteConfirmDesc': "This can't be undone.",
    'photoDiary.permissionTitle': 'Permission needed',
    'photoDiary.cameraPermissionDesc': 'Please allow camera access to take a photo for your photo diary.',
    'photoDiary.libraryPermissionDesc': 'Please allow photo library access to choose a photo for your photo diary.',
    'photoDiary.mediaLibraryPermissionDesc': 'Please allow photo library access to save your photo diary.',
    'photoDiary.errorLoad': "Couldn't load your photo diary.",
    'photoDiary.errorSave': 'Failed to save your photo diary.',
    'photoDiary.errorDelete': 'Failed to delete your photo diary.',
    'photoDiary.errorSaveImage': 'Failed to save/share the image.',
    'today.video': 'Videos',
    'today.diary': 'Diary',
    'today.presets': 'Sets',
    'today.myRoutines': 'Routines',
    'today.list': 'List',
    'today.timeline': 'Timeline',
    'today.llmBanner': 'Add a routine by describing it',
    'today.empty': 'You have no routines for today.',
    'today.edit': 'Edit',
    'today.cancelRecord': 'Delete record',
    'today.skipToday': 'Skip today',
    'today.close': 'Close',
    'today.save': 'Save',
    'today.timelineEmpty': 'There are no routines with a scheduled time.',
    'today.dontShowAgain': "Don't show this again",
    'today.errorLoad': 'Failed to load routines. Please try again.',
    'today.errorCheck': 'Failed to update the check.',
    'today.errorDelete': 'Failed to delete.',
    'today.errorSaveRecord': 'Failed to save the record.',
    'today.holidayPrefix': 'Today is',
    'today.daySuffix': ' days',
    'today.completedLabel': 'Completed today',
    'today.bestStreakLabel': 'Best streak',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.streakUnit': 'days in a row · all-time best',
    'calendar.noStreakYet': "You don't have a best streak yet.",
    'calendar.legendDone': 'All done',
    'calendar.legendPartial': 'Partially done',
    'calendar.legendMissed': 'Missed required',
    'calendar.viewDiary': 'View diary',
    'calendar.memoSection': 'Notes',
    'calendar.noMemo': 'There are no notes for this day.',
    'calendar.memoEdit': 'Edit',
    'calendar.memoDelete': 'Delete',
    'calendar.memoEditComplete': 'Done',
    'calendar.memoAdd': 'Add',
    'calendar.memoCancelEdit': 'Cancel edit',
    'calendar.memoPlaceholder': 'Add a note (e.g. exam tomorrow)',
    'calendar.todayRoutines': "This day's routines",
    'calendar.noRoutinesThisDay': 'There are no routines scheduled for this day.',
    'calendar.errorCheck': 'Failed to update the check.',
    'calendar.errorSaveMemo': 'Failed to save the note.',
    'calendar.errorDeleteMemo': 'Failed to delete the note.',
    'calendar.weekdaySun': 'Sun',
    'calendar.weekdayMon': 'Mon',
    'calendar.weekdayTue': 'Tue',
    'calendar.weekdayWed': 'Wed',
    'calendar.weekdayThu': 'Thu',
    'calendar.weekdayFri': 'Fri',
    'calendar.weekdaySat': 'Sat',
    'stats.errorLoad': 'Failed to load your stats.',
    'stats.retry': 'Retry',
    'stats.emptyNoRecords': "You don't have any records yet. Check off a routine to get started.",
    'stats.hide': 'Hide',
    'stats.currentStreak': 'Current streak',
    'stats.bestStreak': 'Best streak',
    'stats.allTimeRate': 'All-time completion rate',
    'stats.weekly': 'Weekly',
    'stats.monthly': 'Monthly',
    'stats.last7DaysRate': 'Last 7 days',
    'stats.last30DaysRate': 'Last 30 days',
    'stats.completedSuffix': 'completed',
    'stats.categoryAll': 'All',
    'stats.categoryWeekday': 'Weekdays',
    'stats.categoryWeekend': 'Weekends',
    'stats.summaryNote': "Records from deleted routines are still counted above, up until the day each routine was deleted.",
    'stats.emptyCategoryNoRoutines': 'There are no routines in this category.',
    'stats.emptyAllHidden': 'There are no stats to show — everything is currently hidden.',
    'stats.emptyNoActiveRoutines': 'There are no active routines.',
    'stats.hiddenCollapse': 'Hide hidden items ▲',
    'stats.hiddenExpandPrefix': 'Show ',
    'stats.hiddenExpandSuffix': ' hidden ▼',
    'stats.unhide': 'Unhide',
    'myRoutines.filterAll': 'All',
    'myRoutines.filterDaily': 'Daily',
    'myRoutines.filterWeekday': 'Weekdays',
    'myRoutines.filterWeekend': 'Weekends',
    'myRoutines.filterCustom': 'Custom days',
    'myRoutines.filterOnce': 'One-time',
    'myRoutines.onceActive': 'One-time',
    'myRoutines.oncePast': 'Past one-time',
    'myRoutines.repeatDaily': 'Daily',
    'myRoutines.repeatWeekday': 'Weekdays',
    'myRoutines.repeatWeekend': 'Weekends',
    'myRoutines.repeatCustom': 'Custom days',
    'myRoutines.repeatOnce': 'One-time',
    'myRoutines.noScheduledTime': 'No time set',
    'myRoutines.paused': 'Paused',
    'myRoutines.requiredSuffix': ' · Required',
    'myRoutines.skippedTodaySuffix': ' · Skipped today',
    'myRoutines.addToToday': "Add to today's list",
    'myRoutines.delete': 'Delete',
    'myRoutines.errorUnskip': 'Failed to undo the skip.',
    'myRoutines.errorLoad': 'Failed to load routines.',
    'myRoutines.errorDelete': 'Failed to delete.',
    'myRoutines.subtitle': 'You can view and edit all your routines here.',
    'myRoutines.routineTrash': 'Routine Recovery',
    'myRoutines.groupRepeat': 'Repeat',
    'myRoutines.groupPreset': 'Sets',
    'myRoutines.noPresets': "You haven't created any sets yet.",
    'myRoutines.selectedCountSuffix': ' selected',
    'myRoutines.selectAll': 'Select all',
    'myRoutines.deselectAll': 'Deselect all',
    'myRoutines.bulkDelete': 'Select & delete',
    'myRoutines.dragHint': 'Press and hold ≡ to drag and reorder.',
    'myRoutines.emptyChoosePreset': 'Please choose a set above.',
    'myRoutines.emptyNoMatch': 'There are no matching routines.',
    'myRoutines.deleteRoutineTitle': 'Delete this routine?',
    'myRoutines.deleteRoutineOnly': 'Delete routine only',
    'myRoutines.deletePresetToo': 'Delete set too',
    'myRoutines.deleteSelectedTitle': 'Delete selected routines?',
    'presets.errorLoad': 'Failed to load sets.',
    'presets.applyError': 'Failed to apply. Please try again.',
    'presets.deleteError': 'Failed to delete. Please try again.',
    'presets.pauseError': 'Failed to process. Please try again.',
    'presets.deleteTitle': 'Delete this set?',
    'presets.newPreset': '+ Create a new set',
    'presets.empty': "You haven't created any sets yet. Try grouping routines you use often, like a weekday routine, weekend routine, or study session.",
    'presets.skipHolidaysSuffix': ' · Skips holidays',
    'presets.applyToToday': "Apply to today's list",
    'presets.edit': 'Edit',
    'presets.bulkManageLabel': 'Manage routines created from this set',
    'presets.pauseAll': 'Pause all',
    'presets.activateAll': 'Activate all',
    'common.check': 'Check',
    'common.tracking': 'Tracking (number)',
    'common.exactTime': 'Exact time',
    'common.instantTime': 'Time check',
    'common.slot': 'Slot',
    'common.required': 'Required',
    'common.done': 'Done',
    'common.add': 'Add',
    'common.confirm': 'OK',
    'presetForm.errorLoadSlots': 'Failed to load slot information.',
    'presetForm.errorLoadFavorites': 'Failed to load favorites.',
    'presetForm.errorLoadPreset': 'Failed to load the set.',
    'presetForm.errorNameRequired': 'Please enter a name for the set.',
    'presetForm.errorDaysRequired': 'Please select at least one day to repeat.',
    'presetForm.errorItemsRequired': 'Please add at least one item.',
    'presetForm.errorItemTitleRequired': 'Please enter a title for every item.',
    'presetForm.errorTrackingUnitRequired': 'Please enter a unit for tracking items.',
    'presetForm.errorSave': 'Failed to save. Please try again.',
    'presetForm.errorDelete': 'Failed to delete.',
    'presetForm.nameLabel': 'Set name',
    'presetForm.namePlaceholder': 'e.g. Weekday routine',
    'presetForm.repeatLabel': 'Repeat',
    'presetForm.skipHolidays': 'Skip holidays',
    'presetForm.itemsSection': 'Items',
    'presetForm.itemTitlePlaceholder': 'Routine title',
    'presetForm.trackingUnitPlaceholder': 'Type your own (e.g. times)',
    'presetForm.addItem': '+ Add item',
    'presetForm.addFromFavorite': 'Add from favorites',
    'presetForm.saveEdit': 'Save changes',
    'presetForm.create': 'Create',
    'presetForm.deletePreset': 'Delete set',
    'presetForm.createdTitle': 'Set created',
    'presetForm.updatedTitle': "Applied to today's list",
    'presetForm.addedSuffix': 'added',
    'presetForm.removedSuffix': 'removed',
    'favorites.errorDelete': 'Failed to delete.',
    'favorites.addFavorite': '+ Add favorite',
    'favorites.empty': 'Save routines you use often as favorites to quickly reuse them when adding a routine or building a set.',
    'favorites.sectionCheck': 'Check type',
    'favorites.sectionTracking': 'Tracking type',
    'favoriteForm.errorLoadSlots': 'Failed to load slot information.',
    'favoriteForm.errorLoadFavorite': 'Failed to load the favorite.',
    'favoriteForm.errorTitleRequired': 'Please enter a title.',
    'favoriteForm.errorTrackingUnitRequired': 'Please enter a tracking unit.',
    'favoriteForm.errorSlotRequired': 'Please choose a slot.',
    'favoriteForm.errorSave': 'Failed to save.',
    'favoriteForm.errorDelete': 'Failed to delete.',
    'favoriteForm.titleLabel': 'Title',
    'favoriteForm.titlePlaceholder': 'e.g. Stretching',
    'favoriteForm.typeLabel': 'Type',
    'favoriteForm.unitLabel': 'Unit',
    'favoriteForm.timeLabel': 'Time',
    'favoriteForm.saveEdit': 'Save changes',
    'favoriteForm.addToFavorites': 'Add to favorites',
    'videos.myVideos': 'My Videos',
    'videos.recommended': 'Recommended',
    'categoryVideoGrid.addCategory': '+ Category',
    'categoryVideoGrid.addMyVideo': '+ Add my video',
    'categoryVideoGrid.renameCategory': 'Rename',
    'categoryVideoGrid.deletedCategoriesLink': 'Deleted categories',
    'categoryVideoGrid.emptyVideosLine1': "You haven't added any videos yet.",
    'categoryVideoGrid.emptyVideosLine2': 'Grab one from Recommended, or add your own.',
    'categoryVideoGrid.addVideoModalTitle': 'Add my video',
    'categoryVideoGrid.addVideoModalDesc': 'Paste a YouTube link to auto-fill the title and channel. Only visible to you.',
    'categoryVideoGrid.categoryModalTitleCreate': 'Add category',
    'categoryVideoGrid.categoryModalTitleRename': 'Rename category',
    'categoryVideoGrid.categoryNamePlaceholder': 'Category name',
    'categoryVideoGrid.trashModalDesc': "Categories you created can be restored here within 3 days of deletion. After 3 days, the videos inside are permanently deleted too.",
    'categoryVideoGrid.emptyDeletedCategories': 'There are no deleted categories.',
    'categoryVideoGrid.restore': 'Restore',
    'categoryVideoGrid.hardDelete': 'Delete now',
    'categoryVideoGrid.hiddenDefaultsSectionTitle': 'Deleted default categories',
    'categoryVideoGrid.hiddenDefaultsDesc': "Default categories can be recreated anytime, with no 3-day limit. Our default videos will be added back automatically, but any videos you added yourself are already gone and won't return.",
    'categoryVideoGrid.emptyHiddenDefaults': 'There are no deleted default categories.',
    'categoryVideoGrid.recreateDefaults': 'Recreate default categories',
    'categoryVideoGrid.confirmDeleteVideoTitleLinked': 'This video is linked to routines',
    'categoryVideoGrid.confirmDeleteVideoTitleSimple': 'Delete this video?',
    'categoryVideoGrid.deleteFailedTitle': 'Delete failed',
    'categoryVideoGrid.deleteVideoFailedDefault': 'Failed to delete the video.',
    'categoryVideoGrid.alreadyAddedError': 'This video is already in this category.',
    'categoryVideoGrid.addVideoFailedDefault': 'Failed to add the video.',
    'categoryVideoGrid.saveCategoryFailedDefault': 'Failed to save.',
    'categoryVideoGrid.deleteCategoryConfirmTitle': 'Delete this category?',
    'categoryVideoGrid.deleteDefaultCategoryWarningTitle': "Added videos can't be recovered",
    'categoryVideoGrid.deleteCategoryFailed': 'Failed to delete the category.',
    'categoryVideoGrid.recreateFailedTitle': 'Failed',
    'categoryVideoGrid.recreateFailedDesc': 'Failed to recreate default categories.',
    'categoryVideoGrid.restoreFailedTitle': 'Restore failed',
    'categoryVideoGrid.restoreFailedDesc': 'Failed to restore.',
    'categoryVideoGrid.hardDeleteConfirmTitle': 'Delete permanently?',
    'categoryVideoGrid.hardDeleteConfirmDesc': "This deletes it right now instead of waiting 3 days. This can't be undone.",
    'categoryVideoGrid.hardDeleteFailedDesc': 'Failed to delete.',
    'recommendedVideoGrid.notReady': "This category's videos are still being prepared.",
    'recommendedVideoGrid.addToMyGrid': '+ Add to my grid',
    'recommendedVideoGrid.pickCategoryTitle': 'Which category should this go in?',
    'recommendedVideoGrid.pickCategoryEmpty': 'Create a category in the "My Videos" tab first.',
    'recommendedVideoGrid.addFailedTitle': 'Add failed',
    'recommendedVideoGrid.addFailedDefault': 'Failed to add the video.',
    'videoPlayer.loadFailed': 'Failed to load the video.',
    'videoPlayer.visitChannel': 'Visit channel ›',
    'common.minuteShort': 'm',
    'common.hourShort': 'h',
    'routineForm.errorLoadRoutine': 'Failed to load routine details.',
    'routineForm.errorFavoriteApply': 'Failed to add from favorites.',
    'routineForm.photoUploadFailedTitle': 'Saved',
    'routineForm.photoUploadFailedDesc': 'The photo upload failed though. Please attach it again later.',
    'routineForm.photoPermissionTitle': 'Photo access is turned off',
    'routineForm.photoPermissionDesc': 'Please allow photo access in your device settings.',
    'routineForm.loadFromFavorite': 'Load from favorites',
    'routineForm.favoriteHintLoad': 'Load a saved routine template to add it right away, or edit it before adding.',
    'routineForm.titlePlaceholder': 'e.g. Drink water in the morning',
    'routineForm.instantHint': 'Like "wake up at 8" — doesn\'t take up time, just a check at that moment.',
    'routineForm.minus30': '-30m',
    'routineForm.plus30': '+30m',
    'routineForm.plus1h': '+1h',
    'routineForm.plus2h': '+2h',
    'routineForm.reset': 'Reset',
    'routineForm.videoConnectLabel': 'Linked video',
    'routineForm.selectVideo': 'Choose a video',
    'routineForm.memoLabel': 'Memo',
    'routineForm.memoPlaceholder': 'Add a short note about this routine (optional)',
    'routineForm.photoLabel': 'Photo',
    'routineForm.photoAttached': '1 photo attached',
    'routineForm.addPhoto': 'Add a photo',
    'routineForm.addToFavoritesLabel': 'Add to favorites',
    'routineForm.addToFavoritesHint': 'Turn this on to save it as a template you can quickly add again later.',
    'routineForm.deleteRoutineButton': 'Delete routine',
    'routineForm.applyNow': 'Add now',
    'routineForm.applyToFormEdit': 'Edit before adding',
    'slotSettings.errorLoad': 'Failed to load slot information.',
    'slotSettings.errorSave': 'Failed to save.',
    'slotSettings.notifyPermissionTitle': 'Notification permission is turned off',
    'slotSettings.notifyPermissionDesc': 'Please allow notifications in your device settings.',
    'slotSettings.noticeDesc': 'Turning on a slot notification sends a daily alert at the start of that time block. If you turn on the "Before bed" notification, you\'ll also get a reminder on days when you still have required routines left unchecked by then. "Note notifications" can be turned on or off separately from the morning routine notification — on days both are on, they\'re combined into a single notification sent at the morning time.',
    'slotSettings.noticeNote': "ⓘ Morning and note notifications recalculate their next send time each time you open the app. If you don't open the app for several days, they may not arrive during that time — if notifications stop coming, try opening the app once.",
    'slotSettings.modeCheck': 'Check',
    'slotSettings.modeExact': 'Exact time',
    'slotSettings.hintInstant': 'Checks at this exact moment (e.g. 7:00 AM)',
    'slotSettings.hintExact': 'Uses this whole time block as a slot (e.g. 7:00–8:00 AM)',
    'slotSettings.memoNotifyLabel': 'Note notification',
    'slotSettings.memoNotifyHint': 'Sent at this time, on or off independent of the morning routine notification.',
    'routineTrash.errorRestore': 'Failed to restore.',
    'routineTrash.errorCleanup': 'Failed to clean up.',
    'routineTrash.cleanup': 'Clean up',
    'routineTrash.selectCleanup': 'Select & clean up',
    'routineTrash.descLine1': "You can restore deleted routines here anytime. Completion records stay safely stored, so there's no need to worry.",
    'routineTrash.descLine2': 'A set (a routine bundle) is automatically deleted if not restored within 2 weeks. If you\'d rather not wait 2 weeks, tap "Select & clean up" to delete it now (the routines linked to it won\'t be deleted).',
    'routineTrash.empty': 'There are no deleted items.',
    'routineTrash.restorePreset': 'Restore set',
    'routineTrash.cleanupConfirmTitle': 'Clean up now?',
    'routineTrash.cleanupConfirmDo': 'Clean up',
    'llmInput.quotaTitle': "You've used all your free AI parses",
    'llmInput.quotaBody': "Paid plans are coming soon, so please hang tight! Simple sentences like \"every day at 7 AM\" can still be added for free without AI.",
    'llmInput.tryPlainAgain': 'Try a simpler sentence',
    'llmInput.addManually': 'Add manually',
    'llmInput.remainingQuotaPrefix': '',
    'llmInput.remainingQuotaSuffix': ' left',
    'llmInput.placeholder': 'e.g. Drink 8 cups of water every morning at 7',
    'llmInput.hint': 'Adding these makes it more accurate — when (daily, weekdays, Mon/Wed/Fri), what time (7 AM, quarter past 8), whether it\'s required (must, required), and a count (8 cups, 30 minutes). If your sentence is complex, try the "Analyze with AI" button below.',
    'llmInput.errorBody': "AI parsing is temporarily unavailable. It may take a while to come back, so we'd recommend adding it manually for now.",
    'llmInput.retry': 'Retry',
    'llmInput.analyzing': 'Analyzing...',
    'llmInput.previewButton': 'Create preview',
    'llmInput.aiAnalyzing': 'AI is analyzing...',
    'llmInput.aiAnalyzeButton': 'Analyze with AI',
    'diary.errorLoad': 'Failed to load the diary entry.',
    'diary.errorSave': 'Failed to save. Please try again.',
    'diary.errorDelete': 'Failed to delete.',
    'diary.deleteConfirmTitle': 'Delete this diary entry?',
    'diary.deleteConfirmDesc': "This can't be undone.",
    'diary.placeholder': 'How was your day?',
    'diary.deleteButton': 'Delete entry',
    'diary.titleSuffix': 'Diary',
    'login.subtitle': 'Just describe your day, and your routine builds itself',
    'login.google': 'Continue with Google',
    'login.kakao': 'Continue with Kakao',
    'onboarding.headlineLine1': "Let's make it feel",
    'onboarding.headlineLine2': 'like yours.',
    'onboarding.subhead': 'You can always change the theme color, font, and language later in Settings.',
    'onboarding.themeColor': 'Theme Color',
    'onboarding.font': 'Font',
    'onboarding.language': 'Language',
    'onboarding.start': 'Get Started',
    'nav.preset': 'Set',
    'nav.favorites': 'Favorites',
    'nav.videoPlayer': 'Play Video',
    'nav.tabToday': 'Today',
    'nav.tabCalendar': 'Calendar',
    'nav.tabStats': 'Stats',
    'favoritePicker.title': 'Favorites',
    'favoritePicker.empty': 'You have no saved favorites. Create one from "Manage favorites" below.',
    'favoritePicker.manage': 'Manage favorites',
    'videoPicker.title': 'Linked video',
    'slot.morning': 'Morning',
    'slot.lunch': 'Lunch',
    'slot.evening': 'Evening',
    'slot.beforeSleep': 'Before bed',
    'trackingUnit.cup': 'cup',
    'trackingUnit.count': 'count',
    'trackingUnit.minute': 'min',
    'trackingUnit.page': 'page',
    'trackingUnit.km': 'km',
    'videoCategory.exercise': 'Exercise',
    'videoCategory.beauty': 'Beauty',
    'videoCategory.reading': 'Reading',
    'videoCategory.morningRoutine': 'Morning Routine',
    'videoCategory.mindfulness': 'Mindfulness',
    'videoCategory.study': 'Study & Growth',
    'accentColor.cloud': 'Cloud',
    'accentColor.black': 'Black',
    'accentColor.yellow': 'Yellow',
    'accentColor.sage': 'Green',
    'accentColor.rose': 'Rose',
    'today.addRoutine': '+ Add routine',
    'font.default': 'Default Font',
    'font.rounded': 'Rounded Font',
  },
} as const;

export type TranslationKey = keyof (typeof TRANSLATIONS)['ko'];

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
};

// 훅(useTranslation) 없이도, 특정 언어를 지정해서 문구를 바로 조회할 때 쓴다 — 온보딩 화면처럼
// "확정 전 미리보기"가 필요해서 전역 언어 상태를 아직 안 바꾼 채로 그 언어의 문구를 보여줘야 할 때
export function translate(language: Language, key: TranslationKey): string {
  return TRANSLATIONS[language][key] ?? TRANSLATIONS[DEFAULT_LANGUAGE][key];
}

function contextValueFor(language: Language, setLanguage: (lang: Language) => void): LanguageContextValue {
  return {
    language,
    setLanguage,
    t: (key) => translate(language, key),
  };
}

const LanguageContext = createContext<LanguageContextValue>(contextValueFor(DEFAULT_LANGUAGE, () => {}));

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(DEFAULT_LANGUAGE);

  useEffect(() => {
    (async () => {
      const saved = await AsyncStorage.getItem(STORAGE_KEY);
      if (saved === 'ko' || saved === 'en') setLanguageState(saved);
    })();
  }, []);

  function setLanguage(lang: Language) {
    setLanguageState(lang);
    AsyncStorage.setItem(STORAGE_KEY, lang);
  }

  const value = useMemo(() => contextValueFor(language, setLanguage), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useTranslation(): LanguageContextValue {
  return useContext(LanguageContext);
}
