-- 유저가 직접 영상 카테고리를 만들고 이름 수정/삭제할 수 있게 함.
-- user_id가 null이면 기본(관리자) 카테고리, 채워져 있으면 그 유저의 커스텀 카테고리.
-- 삭제는 소프트 삭제(deleted_at) 후 3일 뒤 완전 삭제 — 루틴/모음집 복구와 같은 패턴.
alter table public.categories add column user_id uuid references public.users(id) on delete cascade;
alter table public.categories add column deleted_at timestamptz;

-- 기존엔 id를 1~6으로 수동 지정했지만, 유저가 만드는 카테고리는 자동 증가로 발급한다.
alter table public.categories alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.categories', 'id'), (select max(id) from public.categories));

-- 커스텀 카테고리를 완전 삭제할 때 그 안의 영상도 같이 정리(기본 카테고리는 유저가 못 지우니 영향 없음)
alter table public.videos drop constraint videos_category_id_fkey;
alter table public.videos add constraint videos_category_id_fkey
  foreign key (category_id) references public.categories(id) on delete cascade;

-- routines.category_id는 이미 죽은 기능(2026-08-23 UI 제거)이지만, 옛 데이터가 남아있을 수 있어
-- 카테고리 완전 삭제가 막히지 않도록 SET NULL로 변경
alter table public.routines drop constraint routines_category_id_fkey;
alter table public.routines add constraint routines_category_id_fkey
  foreign key (category_id) references public.categories(id) on delete set null;

-- RLS: 기존엔 로그인 유저가 전체 카테고리를 다 볼 수 있었지만, 기본 카테고리 + 내 카테고리만 보이게 좁힌다.
drop policy "로그인 유저 전체 조회" on public.categories;

create policy "기본 카테고리 + 내 카테고리 조회" on public.categories
  for select using (auth.role() = 'authenticated' and (user_id is null or user_id = auth.uid()));

create policy "내 카테고리만 추가" on public.categories
  for insert with check (user_id = auth.uid());

create policy "내 카테고리만 수정" on public.categories
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "내 카테고리만 삭제" on public.categories
  for delete using (user_id = auth.uid());
